"use client";
import {FormEvent,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase/client";
const cats=["Bonecos","Objetos","Miniaturas","Decoração","Outros"];
export function CreateProductForm(){
 const r=useRouter(); const ref=useRef<HTMLInputElement>(null); const [name,setName]=useState(""); const [category,setCategory]=useState("Bonecos"); const [files,setFiles]=useState<FileList|null>(null); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setError("");if(files&&files.length>8){setError("Máximo de 8 fotos.");return;}setBusy(true);try{const res=await fetch('/api/products',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,category})});const j=await res.json();if(!res.ok)throw new Error(j.error||'Erro ao criar produto.');if(files?.length){const sb=createClient();const {data:{user}}=await sb.auth.getUser();if(user){const rows:any[]=[];for(let i=0;i<files.length;i++){const f=files[i];const ext=f.name.split('.').pop()||'jpg';const path=`${user.id}/${j.id}/${crypto.randomUUID()}.${ext}`;const up=await sb.storage.from('product-images').upload(path,f,{contentType:f.type});if(up.error)throw up.error;const {data:url}=sb.storage.from('product-images').getPublicUrl(path);rows.push({product_id:j.id,storage_path:path,public_url:url.publicUrl,sort_order:i});}const ins=await sb.from('product_images').insert(rows);if(ins.error)throw ins.error;}}setName("");setFiles(null);if(ref.current)ref.current.value="";r.refresh();}catch(err:any){setError(err.message||'Erro.')}finally{setBusy(false);}}
 return <form onSubmit={submit} className="card grid"><h2>Novo produto</h2>{error&&<div className="error">{error}</div>}<div className="field"><label>Nome</label><input className="input" value={name} onChange={e=>setName(e.target.value)} required/></div><div className="field"><label>Categoria</label><select className="select" value={category} onChange={e=>setCategory(e.target.value)}>{cats.map(c=><option key={c}>{c}</option>)}</select></div><div className="field"><label>Fotos (até 8)</label><input ref={ref} className="input" type="file" accept="image/*" multiple onChange={e=>setFiles(e.target.files)}/></div><p className="muted">Os cálculos de energia, materiais, mão de obra e preço ficam na aba <b>Precificação</b>.</p><button className="btn btn-primary" disabled={busy}>{busy?'Salvando...':'Cadastrar produto'}</button></form>
}
