"use client";
import {FormEvent,useMemo,useState} from "react";
import {useRouter} from "next/navigation";

type Material={id:string;name:string;category:string;material_type:string;unit:string;quantity_on_hand:number;minimum_stock:number;average_cost:number;supplier?:string;color_name?:string;color_hex?:string;active?:boolean};
const money=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const typeUnit=(t:string)=>t==="Filamento"?"g":t==="Resina"?"ml":"un";
const label=(m:Material)=>`${m.name}${m.color_name?` — ${m.color_name}`:""}`;

export function InventoryManager({materials}:{materials:Material[]}){
 const r=useRouter();
 const [view,setView]=useState<"overview"|"purchase"|"consume"|"material">("overview");
 const [form,setForm]=useState({name:"",category:"Insumos",material_type:"Outro",unit:"un",color_name:"",color_hex:"#808080",minimum_stock:"0",supplier:""});
 const [purchase,setPurchase]=useState({material_id:"",quantity:"",total_cost:"",supplier:"",notes:""});
 const [use,setUse]=useState({material_id:"",quantity:"",description:""});
 const [filter,setFilter]=useState("Todos"); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
 const filtered=useMemo(()=>filter==="Todos"?materials:materials.filter(m=>m.material_type===filter),[materials,filter]);
 const low=materials.filter(m=>Number(m.quantity_on_hand)<=Number(m.minimum_stock)).length;
 const stockValue=materials.reduce((s,m)=>s+Number(m.quantity_on_hand)*Number(m.average_cost),0);
 const counts={Filamento:materials.filter(m=>m.material_type==="Filamento").length,Resina:materials.filter(m=>m.material_type==="Resina").length,Outro:materials.filter(m=>m.material_type==="Outro").length};
 function updateForm(k:string,v:string){const next={...form,[k]:v} as typeof form;if(k==="material_type")next.unit=typeUnit(v);setForm(next)}
 function open(v:typeof view){setError("");setView(v);if(v==="purchase"&&!purchase.material_id&&materials[0])setPurchase(x=>({...x,material_id:materials[0].id}));if(v==="consume"&&!use.material_id&&materials[0])setUse(x=>({...x,material_id:materials[0].id}))}
 async function post(url:string,body:any){const res=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await res.json().catch(()=>({}));if(!res.ok)throw new Error(j.error||"Não foi possível concluir a operação.");}
 async function submit(fn:()=>Promise<void>){setError("");setBusy(true);try{await fn();r.refresh();setView("overview")}catch(e:any){setError(e.message||"Erro inesperado.")}finally{setBusy(false)}}
 function create(e:FormEvent){e.preventDefault();return submit(async()=>{if(!form.name.trim())throw new Error("Informe o nome do material.");if(form.material_type!=="Outro"&&!form.color_name.trim())throw new Error("Informe a cor do material.");await post("/api/materials",form);setForm({...form,name:"",color_name:"",minimum_stock:"0",supplier:""})})}
 function buy(e:FormEvent){e.preventDefault();return submit(async()=>{if(!purchase.material_id)throw new Error("Selecione um material.");if(Number(purchase.quantity)<=0)throw new Error("Informe uma quantidade válida.");if(Number(purchase.total_cost)<0)throw new Error("O valor pago não pode ser negativo.");await post("/api/material-purchases",purchase);setPurchase(x=>({...x,quantity:"",total_cost:"",notes:""}))})}
 function consume(e:FormEvent){e.preventDefault();return submit(async()=>{if(!use.material_id)throw new Error("Selecione um material.");if(Number(use.quantity)<=0)throw new Error("Informe uma quantidade válida.");await post("/api/stock-movements",{...use,quantity:-Math.abs(Number(use.quantity)),movement_type:"manual_consumption"});setUse(x=>({...x,quantity:"",description:""}))})}
 const selected=materials.find(m=>m.id===purchase.material_id); const selectedUse=materials.find(m=>m.id===use.material_id);
 return <div className="grid" style={{gap:20}}>
  <div className="section-title"><div><h1>🛒 Gastos e compras</h1><p className="muted">Controle compras, consumo, estoque e custos dos materiais em um único fluxo.</p></div><button className="btn btn-primary" onClick={()=>open("purchase")}>＋ Registrar compra</button></div>
  {error&&<div className="error" role="alert">{error}</div>}
  <div className="form-grid" style={{gridTemplateColumns:"repeat(4,minmax(0,1fr))"}}>
   <div className="card"><span className="muted">Materiais cadastrados</span><h2 style={{margin:"6px 0 0"}}>{materials.length}</h2></div>
   <div className="card"><span className="muted">Valor em estoque</span><h2 style={{margin:"6px 0 0"}}>{money(stockValue)}</h2></div>
   <div className="card"><span className="muted">Estoque baixo</span><h2 style={{margin:"6px 0 0"}}>{low}</h2></div>
   <div className="card"><span className="muted">Filamentos / Resinas</span><h2 style={{margin:"6px 0 0"}}>{counts.Filamento} / {counts.Resina}</h2></div>
  </div>
  <div className="card" style={{padding:8}}><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{([["overview","📦 Estoque"],["purchase","🛒 Compra"],["consume","➖ Consumo"],["material","＋ Material"]] as const).map(([v,t])=><button key={v} type="button" className={`btn ${view===v?"btn-primary":"btn-secondary"}`} onClick={()=>open(v)}>{t}</button>)}</div></div>
  {view==="material"&&<form className="card grid" onSubmit={create}><div className="section-title"><div><h2>Novo material</h2><p className="muted">Cadastre primeiro o material para poder comprar ou consumir.</p></div><button type="button" className="btn btn-secondary" onClick={()=>open("overview")}>Cancelar</button></div><div className="form-grid"><div className="field"><label>Nome / marca</label><input className="input" value={form.name} onChange={e=>updateForm("name",e.target.value)} placeholder="Ex.: PLA Matte / Resina Standard" required/></div><div className="field"><label>Tipo</label><select className="select" value={form.material_type} onChange={e=>updateForm("material_type",e.target.value)}><option>Filamento</option><option>Resina</option><option>Outro</option></select></div><div className="field"><label>Categoria</label><select className="select" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Insumos</option><option>Ferramentas</option><option>Maquinários</option></select></div><div className="field"><label>Unidade</label><input className="input" value={form.unit} readOnly/></div></div>{form.material_type!=="Outro"&&<div className="form-grid"><div className="field"><label>Cor</label><input className="input" value={form.color_name} onChange={e=>setForm({...form,color_name:e.target.value})} placeholder="Preto, Branco, Vermelho..." required/></div><div className="field"><label>Cor visual</label><input className="input" type="color" value={form.color_hex} onChange={e=>setForm({...form,color_hex:e.target.value})} style={{height:42,padding:4}}/></div></div>}<div className="form-grid"><div className="field"><label>Estoque mínimo ({form.unit})</label><input className="input" type="number" step="0.001" min="0" value={form.minimum_stock} onChange={e=>setForm({...form,minimum_stock:e.target.value})}/></div><div className="field"><label>Fornecedor</label><input className="input" value={form.supplier} onChange={e=>setForm({...form,supplier:e.target.value})}/></div></div><button className="btn btn-primary" disabled={busy}>Cadastrar material</button></form>}
  {view==="purchase"&&<form className="card grid" onSubmit={buy}><div className="section-title"><div><h2>🛒 Registrar compra</h2><p className="muted">O valor pago define o custo desta entrada no estoque.</p></div><button type="button" className="btn btn-secondary" onClick={()=>open("overview")}>Cancelar</button></div><div className="field"><label>Material</label><select className="select" value={purchase.material_id} onChange={e=>setPurchase({...purchase,material_id:e.target.value})} disabled={!materials.length} required><option value="">{materials.length?"Selecione o material":"Cadastre um material primeiro"}</option>{materials.map(m=><option key={m.id} value={m.id}>{label(m)} · {m.unit}</option>)}</select></div><div className="form-grid"><div className="field"><label>Quantidade ({selected?.unit||"un"})</label><input className="input" type="number" step="0.001" min="0.001" value={purchase.quantity} onChange={e=>setPurchase({...purchase,quantity:e.target.value})} required/></div><div className="field"><label>Valor total pago</label><input className="input" type="number" step="0.01" min="0" value={purchase.total_cost} onChange={e=>setPurchase({...purchase,total_cost:e.target.value})} required/></div><div className="field"><label>Fornecedor</label><input className="input" value={purchase.supplier} onChange={e=>setPurchase({...purchase,supplier:e.target.value})}/></div></div><div className="card" style={{background:"var(--muted-bg,rgba(0,0,0,.03))"}}><strong>Custo desta entrada: </strong>{purchase.quantity&&purchase.total_cost?`${money(Number(purchase.total_cost)/Number(purchase.quantity))}/${selected?.unit||"un"}`:"Informe quantidade e valor"}</div><button className="btn btn-primary" disabled={busy||!materials.length}>{busy?"Salvando...":"Adicionar ao estoque"}</button></form>}
  {view==="consume"&&<form className="card grid" onSubmit={consume}><div className="section-title"><div><h2>➖ Registrar consumo</h2><p className="muted">Use para perdas, testes, manutenção ou outros gastos manuais.</p></div><button type="button" className="btn btn-secondary" onClick={()=>open("overview")}>Cancelar</button></div><div className="form-grid"><div className="field"><label>Material</label><select className="select" value={use.material_id} onChange={e=>setUse({...use,material_id:e.target.value})} disabled={!materials.length} required><option value="">{materials.length?"Selecione o material":"Cadastre um material primeiro"}</option>{materials.map(m=><option key={m.id} value={m.id}>{label(m)} · {m.unit}</option>)}</select></div><div className="field"><label>Quantidade ({selectedUse?.unit||"un"})</label><input className="input" type="number" step="0.001" min="0.001" value={use.quantity} onChange={e=>setUse({...use,quantity:e.target.value})} required/></div><div className="field"><label>Motivo</label><input className="input" value={use.description} onChange={e=>setUse({...use,description:e.target.value})} placeholder="Teste, impressão perdida, manutenção..."/></div></div><button className="btn btn-primary" disabled={busy||!materials.length}>{busy?"Salvando...":"Baixar material"}</button></form>}
  {view==="overview"&&<><div className="section-title"><div><h2>Estoque atual</h2><p className="muted">Filtre rapidamente e identifique itens que precisam de reposição.</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{["Todos","Filamento","Resina","Outro"].map(x=><button key={x} type="button" className={`btn btn-sm ${filter===x?"btn-primary":"btn-secondary"}`} onClick={()=>setFilter(x)}>{x}</button>)}</div></div><div className="card table-wrap"><table><thead><tr><th>Material</th><th>Tipo</th><th>Estoque</th><th>Custo</th><th>Valor</th><th>Status</th></tr></thead><tbody>{filtered.map(m=><tr key={m.id}><td><div style={{display:"flex",alignItems:"center",gap:8}}>{m.material_type!=="Outro"&&<span style={{width:14,height:14,borderRadius:"50%",background:m.color_hex||"#888",border:"1px solid #999",flex:"0 0 auto"}}/>}<div><strong>{m.name}</strong><div className="muted" style={{fontSize:12}}>{m.color_name||m.category}</div></div></div></td><td>{m.material_type}</td><td><strong>{Number(m.quantity_on_hand).toLocaleString("pt-BR",{maximumFractionDigits:3})}</strong> {m.unit}</td><td>{money(Number(m.average_cost))}/{m.unit}</td><td>{money(Number(m.quantity_on_hand)*Number(m.average_cost))}</td><td><span className={`badge ${Number(m.quantity_on_hand)<=Number(m.minimum_stock)?"yellow":"green"}`}>{Number(m.quantity_on_hand)<=Number(m.minimum_stock)?"Reposição":"Normal"}</span></td></tr>)}{!filtered.length&&<tr><td colSpan={6} className="muted">Nenhum material encontrado. <button type="button" className="btn btn-secondary btn-sm" onClick={()=>open("material")}>Cadastrar material</button></td></tr>}</tbody></table></div></>}
 </div>
}
