"use client";
import {FormEvent,useMemo,useState} from 'react'; import {useRouter} from 'next/navigation';

type Material={id:string;name:string;category:string;material_type:string;unit:string;quantity_on_hand:number;minimum_stock:number;average_cost:number;supplier?:string;color_name?:string;color_hex?:string;active?:boolean};
const money=(n:number)=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const typeUnit=(t:string)=>t==='Filamento'?'g':t==='Resina'?'ml':'un';
export function InventoryManager({materials}:{materials:Material[]}){
 const r=useRouter();
 const [form,setForm]=useState({name:'',category:'Insumos',material_type:'Outro',unit:'un',color_name:'',color_hex:'#808080',minimum_stock:'0',supplier:''});
 const [purchase,setPurchase]=useState({material_id:materials[0]?.id||'',quantity:'',total_cost:'',supplier:'',notes:''});
 const [use,setUse]=useState({material_id:materials[0]?.id||'',quantity:'',description:''});
 const [filter,setFilter]=useState('Todos'); const [error,setError]=useState('');
 const filtered=useMemo(()=>filter==='Todos'?materials:materials.filter(m=>m.material_type===filter),[materials,filter]);
 function updateForm(k:string,v:string){const next={...form,[k]:v} as typeof form;if(k==='material_type')next.unit=typeUnit(v);setForm(next)}
 async function post(url:string,body:any){const res=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await res.json();if(!res.ok)throw new Error(j.error||'Erro');}
 async function create(e:FormEvent){e.preventDefault();setError('');try{await post('/api/materials',form);setForm({...form,name:'',color_name:'',minimum_stock:'0',supplier:''});r.refresh()}catch(e:any){setError(e.message)}}
 async function buy(e:FormEvent){e.preventDefault();setError('');if(!purchase.material_id){setError('Cadastre um material antes de registrar uma compra.');return;}if(Number(purchase.quantity)<=0||Number(purchase.total_cost)<0){setError('Informe uma quantidade válida e o valor pago.');return;}try{await post('/api/material-purchases',purchase);setPurchase({...purchase,quantity:'',total_cost:'',notes:''});r.refresh()}catch(e:any){setError(e.message)}}
 async function consume(e:FormEvent){e.preventDefault();setError('');if(!use.material_id){setError('Cadastre um material antes de lançar consumo.');return;}if(Number(use.quantity)<=0){setError('Informe uma quantidade válida.');return;}try{await post('/api/stock-movements',{...use,quantity:-Math.abs(Number(use.quantity)),movement_type:'manual_consumption'});setUse({...use,quantity:'',description:''});r.refresh()}catch(e:any){setError(e.message)}}
 const selected=materials.find(m=>m.id===purchase.material_id);
 return <div className="grid" style={{gap:18}}>{error&&<div className="error">{error}</div>}
  <div className="section-title"><div><h2>📦 Gestão de estoque e compras</h2><p className="muted">Materiais, compras, consumo e custos em um único lugar.</p></div><div className="form-grid"><button type="button" className={`btn ${filter==='Todos'?'btn-primary':'btn-secondary'}`} onClick={()=>setFilter('Todos')}>Todos</button><button type="button" className={`btn ${filter==='Filamento'?'btn-primary':'btn-secondary'}`} onClick={()=>setFilter('Filamento')}>Filamentos</button><button type="button" className={`btn ${filter==='Resina'?'btn-primary':'btn-secondary'}`} onClick={()=>setFilter('Resina')}>Resinas</button><button type="button" className={`btn ${filter==='Outro'?'btn-primary':'btn-secondary'}`} onClick={()=>setFilter('Outro')}>Outros</button></div></div>
  <div className="grid two-col">
   <form className="card grid" onSubmit={create}><h2>Novo material</h2><div className="field"><label>Nome / marca</label><input className="input" value={form.name} onChange={e=>updateForm('name',e.target.value)} placeholder="Ex.: PLA Matte / Resina Standard" required/></div><div className="form-grid"><div className="field"><label>Tipo</label><select className="select" value={form.material_type} onChange={e=>updateForm('material_type',e.target.value)}><option>Filamento</option><option>Resina</option><option>Outro</option></select></div><div className="field"><label>Categoria</label><select className="select" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Insumos</option><option>Ferramentas</option><option>Maquinários</option></select></div><div className="field"><label>Unidade de controle</label><input className="input" value={form.unit} readOnly/></div><div className="field"><label>Estoque mínimo</label><input className="input" type="number" step="0.001" min="0" value={form.minimum_stock} onChange={e=>setForm({...form,minimum_stock:e.target.value})}/></div></div>{form.material_type!=='Outro'&&<div className="form-grid"><div className="field"><label>Cor</label><input className="input" value={form.color_name} onChange={e=>setForm({...form,color_name:e.target.value})} placeholder="Ex.: Preto, Vermelho Ferrari" required/></div><div className="field"><label>Cor visual</label><input className="input" type="color" value={form.color_hex} onChange={e=>setForm({...form,color_hex:e.target.value})} style={{height:42,padding:4}}/></div></div>}<div className="field"><label>Fornecedor</label><input className="input" value={form.supplier} onChange={e=>setForm({...form,supplier:e.target.value})}/></div><button className="btn btn-primary">Cadastrar material</button></form>
   <div className="grid"><form className="card grid" onSubmit={buy}><h2>🛒 Registrar compra</h2><div className="field"><label>Material</label><select className="select" value={purchase.material_id} onChange={e=>setPurchase({...purchase,material_id:e.target.value})} disabled={!materials.length} required><option value="">{materials.length?'Selecione o material':'Nenhum material cadastrado'}</option>{materials.map(m=><option key={m.id} value={m.id}>{m.name}{m.color_name?` — ${m.color_name}`:''}</option>)}</select></div><div className="form-grid"><div className="field"><label>Quantidade ({selected?.unit||'un'})</label><input className="input" type="number" step="0.001" min="0.001" value={purchase.quantity} onChange={e=>setPurchase({...purchase,quantity:e.target.value})} required/></div><div className="field"><label>Valor pago</label><input className="input" type="number" step="0.01" min="0" value={purchase.total_cost} onChange={e=>setPurchase({...purchase,total_cost:e.target.value})} required/></div></div><p className="muted">Custo desta compra: {purchase.quantity&&purchase.total_cost?money(Number(purchase.total_cost)/Number(purchase.quantity)):`R$ 0,00`}/{selected?.unit||'un'}</p><button className="btn btn-primary">Adicionar ao estoque</button></form>
    <form className="card grid" onSubmit={consume}><h2>➖ Gasto / consumo manual</h2><div className="field"><label>Material</label><select className="select" value={use.material_id} onChange={e=>setUse({...use,material_id:e.target.value})} disabled={!materials.length} required><option value="">{materials.length?'Selecione o material':'Nenhum material cadastrado'}</option>{materials.map(m=><option key={m.id} value={m.id}>{m.name}{m.color_name?` — ${m.color_name}`:''}</option>)}</select></div><div className="field"><label>Quantidade consumida</label><input className="input" type="number" step="0.001" min="0.001" value={use.quantity} onChange={e=>setUse({...use,quantity:e.target.value})} required/></div><div className="field"><label>Motivo</label><input className="input" value={use.description} onChange={e=>setUse({...use,description:e.target.value})} placeholder="Teste, impressão perdida, manutenção..."/></div><button className="btn btn-secondary">Baixar material</button></form></div>
  </div>
  <div className="card table-wrap"><h2>Estoque atual</h2><table><thead><tr><th>Material</th><th>Tipo</th><th>Cor</th><th>Estoque</th><th>Custo por unidade</th><th>Valor em estoque</th><th>Status</th></tr></thead><tbody>{filtered.map(m=><tr key={m.id}><td>{m.name}</td><td>{m.material_type}</td><td>{m.material_type!=='Outro'?<span style={{display:'inline-flex',alignItems:'center',gap:7}}><span style={{width:16,height:16,borderRadius:'50%',background:m.color_hex||'#888',border:'1px solid #999'}}></span>{m.color_name||'-'}</span>:'-'}</td><td>{Number(m.quantity_on_hand).toLocaleString('pt-BR',{maximumFractionDigits:3})} {m.unit}</td><td>{money(Number(m.average_cost))}/{m.unit}</td><td>{money(Number(m.quantity_on_hand)*Number(m.average_cost))}</td><td><span className={`badge ${Number(m.quantity_on_hand)<=Number(m.minimum_stock)?'yellow':'green'}`}>{Number(m.quantity_on_hand)<=Number(m.minimum_stock)?'Estoque baixo':'Normal'}</span></td></tr>)}{!filtered.length&&<tr><td colSpan={7} className="muted">Nenhum material cadastrado.</td></tr>}</tbody></table></div>
 </div>
}
