"use client";
import {useRef,useState} from "react"; import {useRouter} from "next/navigation"; import {createClient} from "@/lib/supabase/client";
type Img={id:string;public_url:string;storage_path:string;sort_order:number};
type Product={id:string;name:string;sku?:string|null;description?:string|null;sale_price:number;estimated_cost:number;category:string;active:boolean;images:Img[]};
const cats=["Bonecos","Objetos","Miniaturas","Decoração","Outros"];
export function ProductEditor({product}:{product:Product}){const r=useRouter(); const fileRef=useRef<HTMLInputElement>(null); const [open,setOpen]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [name,setName]=useState(product.name); const [price,setPrice]=useState(String(product.sale_price)); const [cost,setCost]=useState(String(product.estimated_cost)); const [category,setCategory]=useState(product.category||"Bonecos"); const [images,setImages]=useState(product.images||[]);
 async function save(){setBusy(true);setError(""); const res=await fetch(`/api/products/${product.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,sale_price:Number(price),estimated_cost:Number(cost),category})}); const j=await res.json(); if(!res.ok){setError(j.error||"Erro");setBusy(false);return;} setBusy(false); setOpen(false); r.refresh();}
 async function upload(files:FileList|null){if(!files||!files.length)return; if(images.length+files.length>8){setError("Cada produto pode ter no máximo 8 fotos.");return;} setBusy(true);setError(""); const sb=createClient(); const {data:{user}}=await sb.auth.getUser(); if(!user){setError("Sessão expirada.");setBusy(false);return;} const paths=[]; for(let i=0;i<files.length;i++){const f=files[i]; const ext=f.name.split(".").pop()?.toLowerCase()||"jpg"; const path=`${user.id}/${product.id}/${crypto.randomUUID()}.${ext}`; const up=await sb.storage.from("product-images").upload(path,f,{upsert:false,contentType:f.type}); if(up.error){setError(up.error.message);setBusy(false);return;} const {data:url}=sb.storage.from("product-images").getPublicUrl(path); paths.push({product_id:product.id,storage_path:path,public_url:url.publicUrl,sort_order:images.length+i});}
 const ins=await sb.from("product_images").insert(paths).select("id,public_url,storage_path,sort_order"); if(ins.error){setError(ins.error.message);setBusy(false);return;} setImages([...images,...(ins.data as Img[])]);setBusy(false);r.refresh();}
 async function remove(img:Img){if(!confirm("Remover esta foto?"))return; setBusy(true); const res=await fetch(`/api/product-images/${img.id}`,{method:"DELETE"}); const j=await res.json(); if(!res.ok)setError(j.error||"Erro"); else setImages(images.filter(x=>x.id!==img.id)); setBusy(false);r.refresh();}
 return <>{open&&<div className="modal-backdrop"><div className="modal card"><div className="section-title"><h2>Editar produto</h2><button className="btn btn-secondary" onClick={()=>setOpen(false)}>Fechar</button></div>{error&&<div className="error">{error}</div>}<div className="form-grid"><div className="field"><label>Nome</label><input className="input" value={name} onChange={e=>setName(e.target.value)}/></div><div className="field"><label>Categoria</label><select className="select" value={category} onChange={e=>setCategory(e.target.value)}>{cats.map(c=><option key={c}>{c}</option>)}</select></div><div className="field"><label>Preço de venda</label><input className="input" type="number" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/></div><div className="field"><label>Custo estimado</label><input className="input" type="number" step="0.01" value={cost} onChange={e=>setCost(e.target.value)}/></div></div><div className="section-title" style={{marginTop:18}}><div><h3>Fotos ({images.length}/8)</h3><p className="muted">A primeira foto será usada como imagem principal.</p></div><button className="btn btn-secondary" disabled={busy||images.length>=8} onClick={()=>fileRef.current?.click()}>Adicionar fotos</button><input ref={fileRef} type="file" accept="image/*" multiple hidden onChange={e=>upload(e.target.files)}/></div><div className="photo-grid">{images.map((img,i)=><div className="photo-item" key={img.id}><img src={img.public_url} alt=""/><div className="photo-caption">{i===0?<span className="badge green">Principal</span>:<span className="badge">#{i+1}</span>}<button className="btn btn-danger btn-sm" onClick={()=>remove(img)}>Remover</button></div></div>)}</div><div className="actions" style={{justifyContent:"flex-end",marginTop:18}}><button className="btn btn-secondary" onClick={()=>setOpen(false)}>Cancelar</button><button className="btn btn-primary" disabled={busy} onClick={save}>{busy?"Salvando...":"Salvar alterações"}</button></div></div></div>}<button className="btn btn-secondary btn-sm" onClick={()=>setOpen(true)}>Editar</button></>}
}
